language: generic
sudo: required
services:
  - docker

before_install:
 - docker build -t oliverdarby/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oliverdarby/react-test npm test

after_success:
  - docker build -t oliverdarby/multi-client ./client
  - docker build -t oliverdarby/multi-nginx ./nginx
  - docker build -t oliverdarby/multi-server ./server
  - docker build -t oliverdarby/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oliverdarby/multi-client
  - docker push oliverdarby/multi-nginx
  - docker push oliverdarby/multi-server
  - docker push oliverdarby/multi-worker

deploy:
 provider: elasticbeanstalk
 region: eu-west-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: 'elasticbeanstalk-eu-west-2-518323440482'
 bucket_path: 'docker-multi'
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY




